### ISSUE TITLE
Scipy int64 / int32 error on OS X Python 3.3

### ISSUE THREAD

**Issue by ariddell** [ariddell/lda#48]
This shows up only under

- OS X, Clang, Python 3.3.5, Numpy 1.7.1

but not

- OS X, Clang, Python 3.4.3, Numpy 1.7.1

```
======================================================================
ERROR: lda.tests.test_lda_transform.TestLDATransform.test_lda_transform_basic_sparse
----------------------------------------------------------------------
testtools.testresult.real._StringException: Traceback (most recent call last):

  File "/Users/travis/build/ariddell/lda-wheel-builder/venv/lib/python3.3/site-packages/lda/tests/test_lda_transform.py", line 85, in test_lda_transform_basic_sparse
    doc_topic_test = model.transform(dtm_test)

  File "/Users/travis/build/ariddell/lda-wheel-builder/venv/lib/python3.3/site-packages/lda/lda.py", line 174, in transform
    WS, DS = lda.utils.matrix_to_lists(X)

  File "/Users/travis/build/ariddell/lda-wheel-builder/venv/lib/python3.3/site-packages/lda/utils.py", line 44, in matrix_to_lists
    if np.count_nonzero(doc_word.sum(axis=1)) != doc_word.shape[0]:

  File "/Users/travis/build/ariddell/lda-wheel-builder/venv/lib/python3.3/site-packages/scipy/sparse/compressed.py", line 586, in sum
    ret[major_index] = value

TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'
```

**Comment by ariddell** [comment]
I'm going to close this. If this is an issue for others please reopen.
